version: "3.7"
services:

  mongo:
    image: mongo:latest
    container_name: mongodb-zero-downtime
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ScalableProgramming
      MONGO_INITDB_ROOT_PASSWORD: ScalableProgrammingPassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  postgres:
    container_name: postgres-zero-downtime
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=ScalableProgramming
      - POSTGRES_PASSWORD=ScalableProgrammingPassword
    ports:
      - '5432:5432'
    volumes: 
      - postgres_data_container:/var/lib/postgresql/data
volumes:
  mongodb_data_container:
  postgres_data_container: